import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"

/**
 * Seeds all products from folder structure. Call: POST /api/seed-all?key=skirting-seed
 * Images use first 5 from each folder (order as-is; reorder in admin later).
 */
export async function POST(request: NextRequest) {
  const key =
    request.headers.get("x-seed-key") ??
    request.nextUrl.searchParams.get("key") ??
    process.env.SEED_KEY
  if (key !== "skirting-seed" && !process.env.SEED_KEY) {
    return NextResponse.json(
      { error: "Missing or invalid seed key. Use header x-seed-key: skirting-seed or ?key=skirting-seed" },
      { status: 401 },
    )
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!supabaseUrl || !serviceKey) {
    return NextResponse.json(
      { error: "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY" },
      { status: 500 },
    )
  }

  const supabase = createClient(supabaseUrl, serviceKey)

  const placeholderImg = "/product/sharp-modern-A3/sharp-modern-A3-skirting-1.png"

  const products: Array<{
    name: string
    slug: string
    image: string
    images: string[]
    led_type: string
    height: string
    height_value: number
    height_options: number[]
    profile: string
    power: string
    features: string[]
    price: number
    description: string
    category: string
    seo_title: string
    seo_description: string
    meta_keywords: string[]
    in_stock: boolean
    is_active: boolean
  }> = [
    // LED skirting
    {
      name: "Sharp Sodern A3",
      slug: "sharp-sodern-a3",
      image: "/product/sharp-modern-A3/sharp-modern-A3-skirting-1.png",
      images: [
        "/product/sharp-modern-A3/sharp-modern-A3-skirting-1.png",
        "/product/sharp-modern-A3/sharp-modern-A3-skirting-2.png",
        "/product/sharp-modern-A3/sharp-modern-A3-skirting-3.png",
        "/product/sharp-modern-A3/sharp-modern-A3-skirting-4.png",
        "/product/sharp-modern-A3/sharp-modern-A3-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Buckle light strip",
      power: "12V DC",
      features: ["Snap-on installation", "Integrated LED channel", "Aluminium", "2500mm length"],
      price: 78,
      description: "LED skirting board with integrated light strip. Aluminium profile in 80mm, 100mm or 120mm height. Black brushed, iron grey, white and rose gold finishes.",
      category: "residential",
      seo_title: "Sharp Sodern A3 LED Skirting Board | Innovation Skirting NZ",
      seo_description: "Sharp Sodern A3 LED skirting board: aluminium profile with integrated LED strip in 80mm, 100mm or 120mm heights. Snap-on installation. Best prices in NZ.",
      meta_keywords: ["LED skirting", "Sharp Sodern A3", "RMS-A3", "aluminium skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Sharp Slim A7",
      slug: "sharp-slim-a7",
      image: "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-1.png",
      images: [
        "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-1.png",
        "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-2.png",
        "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-3.png",
        "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-4.png",
        "/product/minimal-side-light-A7/minimal-side-light-A7-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "5CM buckle light strip",
      power: "12V DC",
      features: ["Compact profile", "Integrated LED", "Snap-on", "Aluminium"],
      price: 76,
      description: "Sharp Slim A7 5cm LED skirting board with buckle light strip. Minimal profile ideal for modern interiors. Aluminium construction.",
      category: "residential",
      seo_title: "Sharp Slim A7 5cm LED Skirting | Innovation Skirting NZ",
      seo_description: "Sharp Slim A7 5cm LED skirting board with buckle light strip. Compact aluminium profile. Best prices in New Zealand.",
      meta_keywords: ["LED skirting 5cm", "Sharp Slim A7", "RMS-A7", "compact skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Inset LED A8",
      slug: "inset-led-a8",
      image: "/product/inset-led-a8/inset-led-a8-skirting-1.png",
      images: [
        "/product/inset-led-a8/inset-led-a8-skirting-1.png",
        "/product/inset-led-a8/inset-led-a8-skirting-2.png",
        "/product/inset-led-a8/inset-led-a8-skirting-3.png",
        "/product/inset-led-a8/inset-led-a8-skirting-4.png",
        "/product/inset-led-a8/inset-led-a8-skirting-5.png",
      ],
      led_type: "With LED",
      height: "8cm",
      height_value: 80,
      height_options: [40, 60, 80, 26, 30, 50],
      profile: "Inset light strip",
      power: "12V DC",
      features: ["Recessed LED channel", "Flush design", "Aluminium"],
      price: 80,
      description: "Inset LED A8 skirting board with built-in light strip channel. Clean flush design for contemporary spaces.",
      category: "residential",
      seo_title: "Inset LED A8 Skirting Board | Innovation Skirting NZ",
      seo_description: "Inset LED A8 skirting board with recessed light strip channel. Flush aluminium profile. Best prices in NZ.",
      meta_keywords: ["inset LED skirting", "RMS-A8", "recessed skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Surface LED A9",
      slug: "surface-led-a9",
      image: "/product/surface-led-a9/surface-led-a9-skirting-1.png",
      images: [
        "/product/surface-led-a9/surface-led-a9-skirting-1.png",
        "/product/surface-led-a9/surface-led-a9-skirting-2.png",
        "/product/surface-led-a9/surface-led-a9-skirting-3.png",
        "/product/surface-led-a9/surface-led-a9-skirting-4.png",
        "/product/surface-led-a9/surface-led-a9-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Surface-mounted light strip",
      power: "12V DC",
      features: ["Surface mount", "Easy installation", "Aluminium"],
      price: 78,
      description: "Surface LED A9 skirting with surface-mounted light strip. Simple installation for retrofit or new build.",
      category: "residential",
      seo_title: "Surface LED A9 Skirting Board | Innovation Skirting NZ",
      seo_description: "Surface LED A9 skirting board with surface-mounted light strip. Easy installation. Best prices in New Zealand.",
      meta_keywords: ["surface LED skirting", "RMS-A9", "surface mount skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Curve LED A12",
      slug: "curve-led-a12",
      image: "/product/curve-led-a12/curve-led-a12-skirting-1.png",
      images: [
        "/product/curve-led-a12/curve-led-a12-skirting-1.png",
        "/product/curve-led-a12/curve-led-a12-skirting-2.png",
        "/product/curve-led-a12/curve-led-a12-skirting-3.png",
        "/product/curve-led-a12/curve-led-a12-skirting-4.png",
        "/product/curve-led-a12/curve-led-a12-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Curved light strip",
      power: "12V DC",
      features: ["Curved profile", "Integrated LED", "Aluminium"],
      price: 84,
      description: "Curve LED A12 skirting board with curved light strip profile. Ideal for curved walls and architectural features.",
      category: "residential",
      seo_title: "Curve LED A12 Skirting Board | Innovation Skirting NZ",
      seo_description: "Curve LED A12 curved LED skirting board. Integrated light strip for curved walls. Best prices in NZ.",
      meta_keywords: ["curved LED skirting", "RMS-A12", "curve skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Elegant LED A32",
      slug: "elegant-led-a32",
      image: "/product/elegant-led-a32/elegant-led-a32-skirting-1.png",
      images: [
        "/product/elegant-led-a32/elegant-led-a32-skirting-1.png",
        "/product/elegant-led-a32/elegant-led-a32-skirting-2.png",
        "/product/elegant-led-a32/elegant-led-a32-skirting-3.png",
        "/product/elegant-led-a32/elegant-led-a32-skirting-4.png",
        "/product/elegant-led-a32/elegant-led-a32-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Elegant light strip",
      power: "12V DC",
      features: ["Elegant design", "Integrated LED", "Premium finish"],
      price: 82,
      description: "Elegant LED A32 skirting board with refined light strip design. Premium aluminium for sophisticated interiors.",
      category: "residential",
      seo_title: "Elegant LED A32 Skirting Board | Innovation Skirting NZ",
      seo_description: "Elegant LED A32 skirting board with refined light strip. Premium aluminium. Best prices in New Zealand.",
      meta_keywords: ["elegant LED skirting", "RMS-A32", "premium skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Up Glow A36",
      slug: "up-glow-a36",
      image: "/product/up-glow-a36/up-glow-a36-skirting-1.png",
      images: [
        "/product/up-glow-a36/up-glow-a36-skirting-1.png",
        "/product/up-glow-a36/up-glow-a36-skirting-2.png",
        "/product/up-glow-a36/up-glow-a36-skirting-3.png",
        "/product/up-glow-a36/up-glow-a36-skirting-4.png",
        "/product/up-glow-a36/up-glow-a36-skirting-5.png",
      ],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Upward-emitting buckle",
      power: "12V DC",
      features: ["Upward glow", "Buckle design", "Ambient lighting"],
      price: 80,
      description: "Up Glow A36 skirting with upward-emitting LED for ambient ceiling wash. Buckle profile for easy installation.",
      category: "residential",
      seo_title: "Up Glow A36 LED Skirting Board | Innovation Skirting NZ",
      seo_description: "Up Glow A36 skirting board with upward-emitting LED. Ambient ceiling wash. Best prices in NZ.",
      meta_keywords: ["upward LED skirting", "RMS-A36", "ambient skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "LED Light Strip",
      slug: "led-light-strip",
      image: placeholderImg,
      images: [placeholderImg, "", "", "", ""],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Light strip",
      power: "12V DC",
      features: ["Flexible", "RGB options", "Compatible with skirting"],
      price: 76,
      description: "LED light strip for use with our LED skirting board range. Flexible, dimmable options. Compatible with all Innovation Skirting LED profiles.",
      category: "residential",
      seo_title: "LED Light Strip for Skirting | Innovation Skirting NZ",
      seo_description: "LED light strip for skirting boards. Flexible, dimmable. Compatible with all our LED skirting profiles. Best prices in NZ.",
      meta_keywords: ["LED light strip", "skirting LED", "light strip NZ", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Transformer & Wiring",
      slug: "transformer-wiring",
      image: placeholderImg,
      images: [placeholderImg, "", "", "", ""],
      led_type: "With LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Accessory",
      power: "12V",
      features: ["Transformer", "Wiring", "LED compatible"],
      price: 70,
      description: "Transformer and wiring accessories for LED skirting board installations. Compatible with all our LED profiles.",
      category: "residential",
      seo_title: "Transformer & Wiring for LED Skirting | Innovation Skirting NZ",
      seo_description: "Transformer and wiring for LED skirting boards. Full compatibility. Best prices in New Zealand.",
      meta_keywords: ["LED transformer", "skirting wiring", "LED accessories NZ", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    // Skirting – no LED
    {
      name: "Classic Clip A1",
      slug: "classic-clip-a1",
      image: "/product/classic-clip-a1/classic-clip-a1-skirting-1.png",
      images: [
        "/product/classic-clip-a1/classic-clip-a1-skirting-1.png",
        "/product/classic-clip-a1/classic-clip-a1-skirting-2.png",
        "/product/classic-clip-a1/classic-clip-a1-skirting-3.png",
        "/product/classic-clip-a1/classic-clip-a1-skirting-4.png",
        "/product/classic-clip-a1/classic-clip-a1-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Classic buckle",
      power: "—",
      features: ["Snap-on clips", "Classic design", "Aluminium"],
      price: 74,
      description: "Classic Clip A1 skirting board with buckle clips. Timeless design, easy snap-on installation. Aluminium construction.",
      category: "residential",
      seo_title: "Classic Clip A1 Skirting Board | Innovation Skirting NZ",
      seo_description: "Classic Clip A1 skirting board with buckle clips. Timeless design. Best prices in New Zealand.",
      meta_keywords: ["classic skirting", "RMS-A1", "buckle skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Minimal Adhesive A2",
      slug: "minimal-adhesive-a2",
      image: "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-1.png",
      images: [
        "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-1.png",
        "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-2.png",
        "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-3.png",
        "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-4.png",
        "/product/minimal-adhesive-a2/minimal-adhesive-a2-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Minimal adhesive",
      power: "—",
      features: ["Adhesive install", "Minimal profile", "Clean lines"],
      price: 76,
      description: "Minimal Adhesive A2 skirting with adhesive installation. Ultra-minimal profile for contemporary spaces.",
      category: "residential",
      seo_title: "Minimal Adhesive A2 Skirting | Innovation Skirting NZ",
      seo_description: "Minimal Adhesive A2 skirting board. Adhesive installation, minimal profile. Best prices in NZ.",
      meta_keywords: ["minimal skirting", "RMS-A2", "adhesive skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Recessed A4",
      slug: "recessed-a4",
      image: "/product/recessed-a4/recessed-a4-skirting-1.png",
      images: [
        "/product/recessed-a4/recessed-a4-skirting-1.png",
        "/product/recessed-a4/recessed-a4-skirting-2.png",
        "/product/recessed-a4/recessed-a4-skirting-3.png",
        "/product/recessed-a4/recessed-a4-skirting-4.png",
        "/product/recessed-a4/recessed-a4-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Recessed installation",
      power: "—",
      features: ["Flush to wall", "Recessed", "Aluminium"],
      price: 76,
      description: "Recessed A4 skirting board for flush wall installation. Clean, integrated look. Aluminium construction.",
      category: "residential",
      seo_title: "Recessed A4 Skirting Board | Innovation Skirting NZ",
      seo_description: "Recessed A4 skirting board for flush installation. Clean integrated look. Best prices in New Zealand.",
      meta_keywords: ["recessed skirting", "RMS-A4", "flush skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Luxe Clip A5",
      slug: "luxe-clip-a5",
      image: "/product/luxe-clip-a5/luxe-clip-a5-skirting-1.png",
      images: [
        "/product/luxe-clip-a5/luxe-clip-a5-skirting-1.png",
        "/product/luxe-clip-a5/luxe-clip-a5-skirting-2.png",
        "/product/luxe-clip-a5/luxe-clip-a5-skirting-3.png",
        "/product/luxe-clip-a5/luxe-clip-a5-skirting-4.png",
        "/product/luxe-clip-a5/luxe-clip-a5-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Luxe buckle",
      power: "—",
      features: ["Luxe finish", "Snap-on", "Premium aluminium"],
      price: 78,
      description: "Luxe Clip A5 skirting board with premium buckle design. Sophisticated profile for high-end interiors.",
      category: "residential",
      seo_title: "Luxe Clip A5 Skirting Board | Innovation Skirting NZ",
      seo_description: "Luxe Clip A5 skirting with premium buckle design. Sophisticated profile. Best prices in NZ.",
      meta_keywords: ["luxe skirting", "RMS-A5", "premium skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Natural Wood A5N",
      slug: "natural-wood-a5n",
      image: placeholderImg,
      images: [placeholderImg, "", "", "", ""],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Natural wood look",
      power: "—",
      features: ["Wood aesthetic", "Clip design", "Aluminium"],
      price: 76,
      description: "Natural Wood A5N skirting board with natural wood grain aesthetic. Clip installation. Aluminium with wood-effect finish.",
      category: "residential",
      seo_title: "Natural Wood A5N Skirting | Innovation Skirting NZ",
      seo_description: "Natural Wood A5N skirting with wood-effect finish. Clip design. Best prices in New Zealand.",
      meta_keywords: ["wood effect skirting", "RMS-A5N", "natural skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Luxe Thick A39",
      slug: "luxe-thick-a39",
      image: "/product/luxe-thick-a39/luxe-thick-a39-skirting-1.png",
      images: [
        "/product/luxe-thick-a39/luxe-thick-a39-skirting-1.png",
        "/product/luxe-thick-a39/luxe-thick-a39-skirting-2.png",
        "/product/luxe-thick-a39/luxe-thick-a39-skirting-3.png",
        "/product/luxe-thick-a39/luxe-thick-a39-skirting-4.png",
        "/product/luxe-thick-a39/luxe-thick-a39-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Luxe extra-thick",
      power: "—",
      features: ["Extra-thick profile", "Luxe design", "Premium aluminium"],
      price: 80,
      description: "Luxe Thick A39 skirting with extra-thick profile. Premium aluminium for bold architectural presence.",
      category: "residential",
      seo_title: "Luxe Thick A39 Skirting Board | Innovation Skirting NZ",
      seo_description: "Luxe Thick A39 extra-thick skirting board. Premium aluminium. Best prices in New Zealand.",
      meta_keywords: ["thick skirting", "RMS-A39", "luxe skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Diamond Clip A13",
      slug: "diamond-clip-a13",
      image: "/product/diamond-clip-a13/diamond-clip-a13-skirting-1.png",
      images: [
        "/product/diamond-clip-a13/diamond-clip-a13-skirting-1.png",
        "/product/diamond-clip-a13/diamond-clip-a13-skirting-2.png",
        "/product/diamond-clip-a13/diamond-clip-a13-skirting-3.png",
        "/product/diamond-clip-a13/diamond-clip-a13-skirting-4.png",
        "/product/diamond-clip-a13/diamond-clip-a13-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Diamond buckle",
      power: "—",
      features: ["Diamond profile", "Snap-on", "Aluminium"],
      price: 76,
      description: "Diamond Clip A13 skirting with distinctive diamond buckle profile. Statement design for modern interiors.",
      category: "residential",
      seo_title: "Diamond Clip A13 Skirting | Innovation Skirting NZ",
      seo_description: "Diamond Clip A13 skirting with diamond buckle profile. Statement design. Best prices in NZ.",
      meta_keywords: ["diamond skirting", "RMS-A13", "statement skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Bevel Clip A16",
      slug: "bevel-clip-a16",
      image: "/product/bevel-clip-a16/bevel-clip-a16-skirting-1.png",
      images: [
        "/product/bevel-clip-a16/bevel-clip-a16-skirting-1.png",
        "/product/bevel-clip-a16/bevel-clip-a16-skirting-2.png",
        "/product/bevel-clip-a16/bevel-clip-a16-skirting-3.png",
        "/product/bevel-clip-a16/bevel-clip-a16-skirting-4.png",
        "/product/bevel-clip-a16/bevel-clip-a16-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Beveled buckle",
      power: "—",
      features: ["Beveled edge", "Clip design", "Aluminium"],
      price: 74,
      description: "Bevel Clip A16 skirting with beveled buckle profile. Angular design for contemporary spaces.",
      category: "residential",
      seo_title: "Bevel Clip A16 Skirting Board | Innovation Skirting NZ",
      seo_description: "Bevel Clip A16 skirting with beveled buckle. Angular design. Best prices in New Zealand.",
      meta_keywords: ["bevel skirting", "RMS-A16", "angular skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Stainless A18",
      slug: "stainless-a18",
      image: "/product/stainless-a18/stainless-a18-skirting-1.png",
      images: [
        "/product/stainless-a18/stainless-a18-skirting-1.png",
        "/product/stainless-a18/stainless-a18-skirting-2.png",
        "/product/stainless-a18/stainless-a18-skirting-3.png",
        "/product/stainless-a18/stainless-a18-skirting-4.png",
        "/product/stainless-a18/stainless-a18-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Stainless steel",
      power: "—",
      features: ["Stainless steel", "Durable", "Commercial grade"],
      price: 84,
      description: "Stainless A18 skirting board in stainless steel. Durable, commercial-grade finish. Ideal for high-traffic areas.",
      category: "commercial",
      seo_title: "Stainless A18 Skirting Board | Innovation Skirting NZ",
      seo_description: "Stainless A18 stainless steel skirting board. Commercial grade. Best prices in New Zealand.",
      meta_keywords: ["stainless skirting", "RMS-A18", "commercial skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Slim 2cm A19",
      slug: "slim-2cm-a19",
      image: "/product/slim-2cm-a19/slim-2cm-a19-skirting-1.png",
      images: [
        "/product/slim-2cm-a19/slim-2cm-a19-skirting-1.png",
        "/product/slim-2cm-a19/slim-2cm-a19-skirting-2.png",
        "/product/slim-2cm-a19/slim-2cm-a19-skirting-3.png",
        "/product/slim-2cm-a19/slim-2cm-a19-skirting-4.png",
        "/product/slim-2cm-a19/slim-2cm-a19-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Ultra-slim 2cm",
      power: "—",
      features: ["2cm profile", "Ultra-slim", "Discreet"],
      price: 72,
      description: "Slim 2cm A19 skirting board. Ultra-slim 2cm profile for minimal, discreet wall-floor junction.",
      category: "residential",
      seo_title: "Slim 2cm A19 Skirting Board | Innovation Skirting NZ",
      seo_description: "Slim 2cm A19 ultra-slim skirting board. Minimal profile. Best prices in New Zealand.",
      meta_keywords: ["2cm skirting", "RMS-A19", "slim skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Seamless Edge A20",
      slug: "seamless-edge-a20",
      image: "/product/seamless-edge-a20/seamless-edge-a20-skirting-1.png",
      images: [
        "/product/seamless-edge-a20/seamless-edge-a20-skirting-1.png",
        "/product/seamless-edge-a20/seamless-edge-a20-skirting-2.png",
        "/product/seamless-edge-a20/seamless-edge-a20-skirting-3.png",
        "/product/seamless-edge-a20/seamless-edge-a20-skirting-4.png",
        "",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Seamless straight edge",
      power: "—",
      features: ["Seamless joints", "Straight edge", "Aluminium"],
      price: 70,
      description: "Seamless Edge A20 skirting with seamless straight edge. Clean lines, invisible joints.",
      category: "residential",
      seo_title: "Seamless Edge A20 Skirting | Innovation Skirting NZ",
      seo_description: "Seamless Edge A20 skirting with seamless joints. Clean lines. Best prices in NZ.",
      meta_keywords: ["seamless skirting", "RMS-A20", "straight edge skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Double Clip A33",
      slug: "double-clip-a33",
      image: "/product/double-clip-a33/double-clip-a33-skirting-1.png",
      images: [
        "/product/double-clip-a33/double-clip-a33-skirting-1.png",
        "/product/double-clip-a33/double-clip-a33-skirting-2.png",
        "/product/double-clip-a33/double-clip-a33-skirting-3.png",
        "/product/double-clip-a33/double-clip-a33-skirting-4.png",
        "/product/double-clip-a33/double-clip-a33-skirting-5.png",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Double-layer buckle",
      power: "—",
      features: ["Double-layer clip", "Robust", "Aluminium"],
      price: 76,
      description: "Double Clip A33 skirting with double-layer buckle design. Robust installation. Aluminium construction.",
      category: "residential",
      seo_title: "Double Clip A33 Skirting Board | Innovation Skirting NZ",
      seo_description: "Double Clip A33 skirting with double-layer buckle. Robust design. Best prices in New Zealand.",
      meta_keywords: ["double clip skirting", "RMS-A33", "robust skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
    {
      name: "Curve Edge A34",
      slug: "curve-edge-a34",
      image: "/product/curve-edge-a34/curve-edge-a34-skirting-1.png",
      images: [
        "/product/curve-edge-a34/curve-edge-a34-skirting-1.png",
        "/product/curve-edge-a34/curve-edge-a34-skirting-2.png",
        "/product/curve-edge-a34/curve-edge-a34-skirting-3.png",
        "/product/curve-edge-a34/curve-edge-a34-skirting-4.png",
        "",
      ],
      led_type: "Without LED",
      height: "4cm / 6cm / 8cm / 26cm / 30cm / 50cm",
      height_value: 80,
      height_options: [40, 60, 80, 260, 300, 500],
      profile: "Curved straight edge",
      power: "—",
      features: ["Curved profile", "Straight edge", "Aluminium"],
      price: 80,
      description: "Curve Edge A34 skirting with curved straight edge. For curved walls and architectural features.",
      category: "residential",
      seo_title: "Curve Edge A34 Skirting | Innovation Skirting NZ",
      seo_description: "Curve Edge A34 curved skirting with straight edge. For curved walls. Best prices in NZ.",
      meta_keywords: ["curved skirting", "RMS-A34", "curve edge skirting", "New Zealand"],
      in_stock: true,
      is_active: true,
    },
  ]

  const results: Array<{ slug: string; ok: boolean; error?: string }> = []

  for (const product of products) {
    const { data, error } = await supabase
      .from("products")
      .upsert(product, { onConflict: "slug" })
      .select("id")
      .single()

    results.push({
      slug: product.slug,
      ok: !error,
      error: error?.message,
    })
  }

  const failed = results.filter((r) => !r.ok)
  return NextResponse.json({
    success: failed.length === 0,
    created: results.filter((r) => r.ok).length,
    failed: failed.length,
    results,
  })
}
